"""
Django settings for testweb project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR指的是我們專案的根路徑，就是最外層mysite的路徑：
# 最裡面的括號是settings.py的路徑，再外面一層是專案mysite的路徑，最外面的括號呢就是mysite資料夾的路徑。
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 用於防止CSRF（Cross-site request forgery）跨站請求偽造攻擊
SECRET_KEY = 'django-insecure-paevx_ryo66m+013zce-&++x&arbgb$=!8=*yel_boz@^8x9jz'
# 是Django網站安全策略的一部分
# SECURITY WARNING: don't run with debug turned on in production!
# 這個會在debug日誌裡輸出錯誤信息，而不是輸入H​​TTP的返回碼。
# 在生產環境中，它應設置為false，因為輸出的錯誤信息，會幫助想要攻擊網站的人。
# DEBUG=True開啟除錯模式，而TEMPLATE_DEBUG=DEBUG則是開啟除錯模式的樣版。
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    #加上這行指的是應用配置文件在(CatalogConfig)/locallibrary/catalog/apps.py裏
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# 代表你的根URLconf的模組名
ROOT_URLCONF = 'testweb.urls'

TEMPLATES = [
    {
        # 要使用的模板后端,内置的模板后端如下,还有django.template.backends.jinja2.Jinja2,
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 在搜索顺序中引擎应该寻找模板源文件的目录,即绝对路径
        'DIRS': [],
        # 設置引擎是否應該在安装的應用程序中
        'APP_DIRS': True,
        # 额外的参数传递给模板后端,可用参数因模板后端而不同
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# Django内置服务器 (如runserver) 的应用程序对象的完整Python路径
# django-admin startproject 执行会创建一个简单的wsgi.py 应用程序 , 并将此设置指向该应用程序
WSGI_APPLICATION = 'testweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# 修改這裡
import os
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR,'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
# 用于检查用户密码强度验证程序的列表
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# zh-Hant中文-漢繁體    Hans	簡體漢字    Hani 漢字
LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True #默認為True，是否啟用自動翻譯系統

USE_L10N = True #默認為False，以本地化格式顯示數字和時間

USE_TZ = False  #默認為True，若使用本地時間，必須設定為False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# 静态文件 (static) 主要指 , CSS , JavaScript , Images这样的文件
STATIC_URL = '/static/'
STATICFILES_DIRS =[os.path.join(BASE_DIR,'static'),]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
